components_manager:
    components:
        mongo-tr:
            dbconnection: mongodb://localhost:27071/DB
        dns-client: 
            fs-task-processor: fs-task-processor
        handler-translations:
            path: /
            method: GET,PATCH
            task_processor: main-task-processor
        server:
            listener:
                port: 8080 
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: warning
                    overflow_behavior: discard 
    task_processors:  
        main-task-processor:  
            worker_threads: 4 
        fs-task-processor: 
            worker_threads: 4
    default_task_processor: main-task-processor 